In [5]:
list1 = [1,2,[3, "List"],4,5]
print(list1)

[1, 2, [3, 'List'], 4, 5]


In [17]:
import numpy as np

num_list  = np.array([1,2,3,4])
print(num_list)

num_copy = [i for i in num_list]
print(num_copy)

num_range = np.arange(10)
print(num_range)

[1 2 3 4]
[1, 2, 3, 4]
[0 1 2 3 4 5 6 7 8 9]


In [18]:
num_list.shape

(4,)

In [21]:
trans_num_list = num_list.transpose()
print(trans_num_list)
trans_num_list.shape

[1 2 3 4]


(4,)

In [23]:
np_range_1 = np.arange(0, 10, 2)
np_range_1

array([0, 2, 4, 6, 8])

In [29]:
np_zeros = np.zeros(10)
print(np_zeros)
print(np_zeros.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)


In [31]:
np_zeros = np.zeros((3,  10))
print(np_zeros)
print(np_zeros.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(3, 10)


In [33]:
np_full = np.full((3, 10), 5)
print(np_full)
print(np_full.shape)

[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]
(3, 10)


In [36]:
np_convert = np.array([[1,2], [2,3]])
print(np_convert)
print(np_convert.shape)

[[1 2]
 [2 3]]
(2, 2)


In [44]:
arr = np.arange(1, 10)
print(arr)
print(arr[1:5])#Does not include upper limit index
print(arr[3:])
print(arr[-3:-1])
print(arr[1:5:2])#Slice with steps
print(arr[::2])#Slice with steps

[1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[4 5 6 7 8 9]
[7 8]
[2 4]
[1 3 5 7 9]


In [55]:
arr_2d = np.arange(1, 11).reshape((5,2))
print(arr_2d)
print(arr_2d[1:2])
print(arr_2d[1:2, 1::])
print(arr_2d[1:4, 1::])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[3 4]]
[[4]]
[[4]
 [6]
 [8]]


In [64]:
#Find square root of each element in array
# arr = np.array([i*i for i in range(10)])
arr = np.square([i for i in range(10)])
print(arr)
print(np.sqrt(arr))


[ 0  1  4  9 16 25 36 49 64 81]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [66]:
print(np.min(arr))
print(np.max(arr))

0
81


In [67]:
np.absolute([1, -2, 4, -5])

array([1, 2, 4, 5])

In [68]:
# np.sin, np.cos, np.log
# these are called universal functions

In [75]:
arr = np.arange(1, 25, 3)
print(f'Original A1-> {arr}')

#This creates a reference to the same array
arr_2 = arr.view()
print(f'Original A2-> {arr_2}')

arr[0] = -1
print(f'After arr modification A1-> {arr}')
print(f'After arr modification A2-> {arr_2}')

arr_2[-1] = -1
print(f'After arr_2 modification A1-> {arr}')
print(f'After arr_2 modification A2-> {arr_2}')

#A shallow copy would be achieved with 
arr_copy = arr.copy()
arr_copy[2] = 10
print(f'After arr_copy modification A1-> {arr}')
print(f'After arr_copy modification A_copy-> {arr_copy}')

Original A1-> [ 1  4  7 10 13 16 19 22]
Original A2-> [ 1  4  7 10 13 16 19 22]
After arr modification A1-> [-1  4  7 10 13 16 19 22]
After arr modification A2-> [-1  4  7 10 13 16 19 22]
After arr_2 modification A1-> [-1  4  7 10 13 16 19 -1]
After arr_2 modification A2-> [-1  4  7 10 13 16 19 -1]
After arr_copy modification A1-> [-1  4  7 10 13 16 19 -1]
After arr_copy modification A_copy-> [-1  4 10 10 13 16 19 -1]


In [89]:
arr = np.arange(0, 25)
print(arr)
print(arr.shape)

arr_2d = arr.reshape((5,5))
print(arr_2d)
print(arr_2d.shape)

print(arr_2d.reshape(-1))
print(arr_2d.flatten())
print(arr_2d.ravel())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
(25,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [91]:
arr_2d = np.arange(0, 25).reshape((5,5))
print(arr_2d)
print(arr_2d.shape)

for x in np.nditer(arr_2d):
    print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(5, 5)
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [94]:
#print even numbers in array
#where return the indexes
arr = np.arange(0, 25)
print(arr[np.where(arr % 2 == 0)[0]])


bool_index_list = [i % 2 == 0 for i in arr]
print(bool_index_list)
print(arr[bool_index_list])

bool_index_list = arr % 2 == 0
print(bool_index_list)
print(arr[bool_index_list])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24]
[True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24]
[ True False  True False  True False  True False  True False  True False
  True False  True False  True False  True False  True False  True False
  True]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24]
