In [5]:
list1 = [1,2,[3, "List"],4,5]
print(list1)

[1, 2, [3, 'List'], 4, 5]


In [17]:
import numpy as np

num_list  = np.array([1,2,3,4])
print(num_list)

num_copy = [i for i in num_list]
print(num_copy)

num_range = np.arange(10)
print(num_range)

[1 2 3 4]
[1, 2, 3, 4]
[0 1 2 3 4 5 6 7 8 9]


In [18]:
num_list.shape

(4,)

In [21]:
trans_num_list = num_list.transpose()
print(trans_num_list)
trans_num_list.shape

[1 2 3 4]


(4,)

In [23]:
np_range_1 = np.arange(0, 10, 2)
np_range_1

array([0, 2, 4, 6, 8])

In [29]:
np_zeros = np.zeros(10)
print(np_zeros)
print(np_zeros.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(10,)


In [31]:
np_zeros = np.zeros((3,  10))
print(np_zeros)
print(np_zeros.shape)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(3, 10)


In [33]:
np_full = np.full((3, 10), 5)
print(np_full)
print(np_full.shape)

[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]
(3, 10)


In [36]:
np_convert = np.array([[1,2], [2,3]])
print(np_convert)
print(np_convert.shape)

[[1 2]
 [2 3]]
(2, 2)


In [44]:
arr = np.arange(1, 10)
print(arr)
print(arr[1:5])#Does not include upper limit index
print(arr[3:])
print(arr[-3:-1])
print(arr[1:5:2])#Slice with steps
print(arr[::2])#Slice with steps

[1 2 3 4 5 6 7 8 9]
[2 3 4 5]
[4 5 6 7 8 9]
[7 8]
[2 4]
[1 3 5 7 9]


In [54]:
arr_2d = np.arange(1, 11).reshape((5,2))
print(arr_2d)
print(arr_2d[1:2])
print(arr_2d[1:2, 1::])
print(arr_2d[1:4, 1::])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[3 4]]
[[4]]
[[4]
 [6]
 [8]]
