In [83]:
import random
import numpy as np


class Perceptron:
    input_size = 30
    input_features = 2
    
    inputs = np.random.rand(30, 2)
    outputs = np.ones((input_size, 1))
    
    weights = np.random.uniform(-1,2, (2,1))
    threshold = np.random.randint(5)
    
    epochs = 1000
    learning_rate = 0.1
         
    def create_test_data_set(self):
        for i in range(self.input_size):
            self.inputs[i] = np.random.randint(2, size=2) 
            self.outputs[i] = self.generate_output(self.inputs[i])
            
    def train(self):
        I = [i for i in range(self.input_size)]#Why not just pick up randomly from the input?
        
        for epoch in range(self.epochs):
            random.shuffle(I)
            for i in I:
                _input = self.inputs[i]
                target = self.outputs[i][0]
                
                y = self.compute_output(self.inputs[i])
                error = target - y
                
                self.weights = np.array([(w + (self.learning_rate * error * _input)) for w in self.weights.transpose()]).transpose()
                self.threshold = self.threshold - (self.learning_rate * error)
                
                
                print(self.weights)
                print(self.threshold)
                # print(f'Error: {error}')
    
    def compute_output(self, input_vector):
        return np.dot(input_vector, self.weights)[0] - self.threshold
            
    def generate_output(self, input_vector):
        return 0 if (2 * input_vector[0] + 3 * input_vector[1] -1) <= 0 else 1
    
    def print_input(self):
        print(self.inputs)
        
    def print_output(self):
        print(self.outputs)
        
    def print_weights(self):
        print(self.weights)
        

In [85]:
p = Perceptron()
p.create_test_data_set()
p.train()
p.print_weights()



[[0.98422775]
 [1.46146791]]
1.0557119574723695
[[0.98422775]
 [1.52089231]]
0.996287552279984
[[0.9333445 ]
 [1.47000906]]
1.0471708035491196
[[0.89772623]
 [1.43439078]]
1.0827890794375146
[[0.89772623]
 [1.43439078]]
0.9745101714937631
[[0.89772623]
 [1.48840272]]
0.9204982327027238
[[0.89772623]
 [1.48840272]]
0.8284484094324513
[[0.89772623]
 [1.52240729]]
0.7944438407266471
[[0.89772623]
 [1.52240729]]
0.7149994566539823
[[0.82721282]
 [1.45189388]]
0.7855128628038964
[[0.92304283]
 [1.45189388]]
0.6896828586158064
[[0.92304283]
 [1.47567278]]
0.6659039612472557
[[0.99732894]
 [1.47567278]]
0.5916178476336387
[[0.99732894]
 [1.47567278]]
0.5324560628702748
[[0.99732894]
 [1.48135111]]
0.5267777348131323
[[0.99732894]
 [1.48135111]]
0.47409996133181903
[[0.99732894]
 [1.480626  ]]
0.47482507623423637
[[0.89701595]
 [1.38031301]]
0.5751380620286405
[[0.82679686]
 [1.31009392]]
0.6453571520847233
[[0.82679686]
 [1.31009392]]
0.580821436876251
[[0.82679686]
 [1.33716667]]
0.553748685

1.1275530801562224

In [89]:
p.print_input()

[[1. 1.]
 [0. 1.]
 [0. 0.]
 [0. 1.]
 [1. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [0. 0.]
 [0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 0.]
 [0. 1.]
 [1. 1.]
 [1. 1.]
 [0. 0.]
 [1. 1.]
 [1. 1.]]


In [90]:
p.print_output()

[[1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]]


In [88]:

p.compute_output([1,0])

0.48988956133500655